version: '3.6'
services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    environment:
      ORACLE_ALLOW_REMOTE: 'true'
      ORACLE_ENABLE_XDB: 'true'
      ORACLE_DISABLE_ASYNCH_IO: 'true'
      APP_USER: mitestuser
      APP_USER_PASSWORD: mitestuser
      ORACLE_USER: 'system'
      ORACLE_PASSWORD: 'oracle'
      #ORACLE_RANDOM_PASSWORD: 'yes'
    ports:
      - 1521:1521
      - 5500:5500
    networks:
      - core_fast-net

networks:
  core_fast-net:
    external: true
